// Writes test/vectors.json: Merkle trees built in TypeScript that contracts/test/MerkleCompat.t.sol
// must verify through CreditEscrow.isInBatch. Run after changing src/merkle.ts:
//   pnpm --filter @policyrouter/policy vectors

import { writeFileSync } from "node:fs";
import { batchTree, proofFor, type Hex32 } from "../src/merkle.ts";

const SIZES = [1, 2, 3, 7, 16];

/** Deterministic, distinct leaves: 0x00..01, 0x00..02, … with the case size in the top byte. */
function leaves(n: number): Hex32[] {
  return Array.from({ length: n }, (_, i) => {
    const top = n.toString(16).padStart(2, "0");
    return `0x${top}${(i + 1).toString(16).padStart(62, "0")}` as Hex32;
  });
}

export function buildVectors() {
  return {
    note: "Generated by packages/policy/scripts/merkle-vectors.ts. Do not edit by hand.",
    cases: SIZES.map((n) => {
      const ls = leaves(n);
      const tree = batchTree(ls);
      return { size: n, root: tree.root, leaves: ls, proofs: ls.map((l) => proofFor(tree, l)) };
    }),
  };
}

export const vectorsPath = new URL("../test/vectors.json", import.meta.url);

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(vectorsPath, `${JSON.stringify(buildVectors(), null, 2)}\n`);
  console.log("wrote packages/policy/test/vectors.json");
}
